#!/usr/bin/python
# Script to add LegacyLogo for Chameleon boot loaders

import sys
import os

vol = str(sys.argv[3])
boot = "/Extra/org.chameleon.Boot.plist"
plist = vol + boot
infile = open(plist, "r")
# check if LegacyLogo has been written or not
LegacyLogoCheck = False

body = ""

for line in infile:
    # if we finish the tags and haven't written LegacyLogo Yet
    if "</dict>" in line and LegacyLogoCheck == False:
        line = "        <key>LegacyLogo</key>\n"
        line += "        <string>Yes</string>\n"
        line += "</dict>\n"
        LegacyLogoCheck = True
        
    body += line
    
infile.close()

outfile = open(plist, "w")
outfile.write(body)
outfile.close()
