#!/usr/bin/python
# Script to add Wake for Chameleon boot loaders

import sys
import os
import shutil

vol = str(sys.argv[3])
boot = "/Extra/org.chameleon.Boot.plist"
plist = vol + boot
if not os.path.exists(plist):
    shutil.copy('/Library/Preferences/SystemConfiguration/com.apple.Boot.plist', plist)

infile = open(plist, "r")
# check if Wake has been written or not
WakeCheck = False

body = ""

for line in infile:
    # if we finish the tags and haven't written Wake Yet
    if "</dict>" in line and WakeCheck == False:
        line = "        <key>Wake</key>\n"
        line += "        <string>Yes</string>\n"
        line += "</dict>\n"
        WakeCheck = True
        
    body += line
    
infile.close()

outfile = open(plist, "w")
outfile.write(body)
outfile.close()
