#!/usr/bin/python
# Script to add CSTUsingSystemIO for Chameleon boot loaders

import sys
import os

vol = str(sys.argv[3])
boot = "/Extra/org.chameleon.Boot.plist"
plist = vol + boot
infile = open(plist, "r")
# check if CSTUsingSystemIO has been written or not
CSTUsingSystemIOCheck = False

body = ""

for line in infile:
    # if we finish the tags and haven't written CSTUsingSystemIO Yet
    if "</dict>" in line and CSTUsingSystemIOCheck == False:
        line = "        <key>CSTUsingSystemIO</key>\n"
        line += "        <string>Yes</string>\n"
        line += "</dict>\n"
        CSTUsingSystemIOCheck = True
        
    body += line
    
infile.close()

outfile = open(plist, "w")
outfile.write(body)
outfile.close()
