#!/bin/bash

set -u

targetVolume="$3"

moduleName="@moduleName@"
moduleFile="@moduleFile@"
logName="@LOG_FILENAME@"
logFile="${targetVolume}/$logName"

# Check if target volume exists
if [[ ! -d "$targetVolume" ]]; then
    echo "$targetVolume volume does not exist!" >&2
    exit 1
fi

exec >>"${logFile}" 2>&1

[[ -f "${targetVolume}/Extra/modules/$moduleFile" ]] && echo "Module $moduleName installed"

exit 0
