MODULE_NAME = ACPICodec
MODULE_DESCRIPTION = This module provides a remplacement for the internal acpi patcher
MODULE_AUTHOR = "Cparm"
MODULE_VERSION = "1.0.0"
MODULE_COMPAT_VERSION = "1.0.0"
MODULE_START = $(MODULE_NAME)_start
MODULE_DEPENDENCIES =

DIR = ACPICodec

MODULE_OBJS = ACPICodec.o acpi_tools.o acpi_codec.o acpidecode.o acpicode.o 

include ../MakeInc.dir