#!/usr/bin/python
# Script to add GUI for Chameleon boot loaders

import sys
import os
import shutil

vol = str(sys.argv[3])
boot = "/Extra/org.chameleon.Boot.plist"
plist = vol + boot
if not os.path.exists(plist):
    shutil.copy('/Library/Preferences/SystemConfiguration/com.apple.Boot.plist', plist)

infile = open(plist, "r")
# check if GUI has been written or not
GUICheck = False

body = ""

for line in infile:
    # if we finish the tags and haven't written GUI Yet
    if "</dict>" in line and GUICheck == False:
        line = "        <key>GUI</key>\n"
        line += "        <string>No</string>\n"
        line += "</dict>\n"
        GUICheck = True
        
    body += line
    
infile.close()

outfile = open(plist, "w")
outfile.write(body)
outfile.close()
