#!/usr/bin/python
# Script to add Graphics_Mode for Chameleon boot loaders

import sys
import os

vol = str(sys.argv[3])
boot = "/Extra/org.chameleon.Boot.plist"
plist = vol + boot
infile = open(plist, "r")
# check if Graphics_Mode has been written or not
Graphics_ModeCheck = False

body = ""

for line in infile:
    # if GraphicsEnabler is there, advance the next line to
    # read past it, and then change the lines to read
    # "<key>GraphicsEnabler<\key>" and "<string>Yes</string>"
    if "<key>GraphicsEnabler</key>" in line:
        line = infile.next()
        line = "        <key>Graphics Mode</key>\n"
        line += "        <string>1440x900x32</string>\n"
        InstantMenuCheck = True

    # if we finish the tags and haven't written Graphics_Mode Yet
    if "</dict>" in line and Graphics_ModeCheck == False:
        line = "        <key>Graphics Mode</key>\n"
        line += "        <string>1440x900x32</string>\n"
        line += "</dict>\n"
        Graphics_ModeCheck = True
        
    body += line
    
infile.close()

outfile = open(plist, "w")
outfile.write(body)
outfile.close()
