#!/usr/bin/python
# Script to add EnableC4State for Chameleon boot loaders

import sys
import os

vol = str(sys.argv[3])
boot = "/Extra/org.chameleon.Boot.plist"
plist = vol + boot
infile = open(plist, "r")
# check if EnableC4State has been written or not
EnableC4StateCheck = False

body = ""

for line in infile:
    # if we finish the tags and haven't written EnableC4State Yet
    if "</dict>" in line and EnableC4StateCheck == False:
        line = "        <key>EnableC4State</key>\n"
        line += "        <string>Yes</string>\n"
        line += "</dict>\n"
        EnableC4StateCheck = True
        
    body += line
    
infile.close()

outfile = open(plist, "w")
outfile.write(body)
outfile.close()
