MODULE_NAME = Keylayout
MODULE_DESCRIPTION = This module provides keylayout functionality
MODULE_AUTHOR = "JrCs"
MODULE_VERSION = "1.2.0"
MODULE_COMPAT_VERSION = "1.2.0"
MODULE_START = $(MODULE_NAME)_start
MODULE_DEPENDENCIES = 

DIR = Keylayout
SUBDIRS += layouts

MODULE_OBJS = Keylayout.o

include ../MakeInc.dir
