#!/usr/bin/python
# Script to add EthernetBuiltIn for Chameleon boot loaders

import sys
import os

vol = str(sys.argv[3])
boot = "/Extra/org.chameleon.Boot.plist"
plist = vol + boot
infile = open(plist, "r")
# check if EthernetBuiltIn has been written or not
EthernetBuiltInCheck = False

body = ""

for line in infile:
    # if we finish the tags and haven't written DropSSDT Yet
    if "</dict>" in line and EthernetBuiltInCheck == False:
        line = "        <key>EthernetBuiltIn</key>\n"
        line += "        <string>Yes</string>\n"
        line += "</dict>\n"
        EthernetBuiltInCheck = True
        
    body += line
    
infile.close()

outfile = open(plist, "w")
outfile.write(body)
outfile.close()
