#!/usr/bin/python
# Script to add GenerateCStates for Chameleon boot loaders

import sys
import os
import shutil

vol = str(sys.argv[3])
boot = "/Extra/org.chameleon.Boot.plist"
plist = vol + boot
if not os.path.exists(plist):
    shutil.copy('/Library/Preferences/SystemConfiguration/com.apple.Boot.plist', plist)

infile = open(plist, "r")
# check if GenerateCStates has been written or not
GenerateCStatesCheck = False

body = ""

for line in infile:
    # if we finish the tags and haven't written GenerateCStates Yet
    if "</dict>" in line and GenerateCStatesCheck == False:
        line = "        <key>GenerateCStates</key>\n"
        line += "        <string>Yes</string>\n"
        line += "</dict>\n"
        GenerateCStatesCheck = True
        
    body += line
    
infile.close()

outfile = open(plist, "w")
outfile.write(body)
outfile.close()
