MODULE_NAME = Resolution
MODULE_VERSION = "1.0.0"
MODULE_COMPAT_VERSION = "1.0.0"
MODULE_START = $(MODULE_NAME)_start
MODULE_DEPENDENCIES = 


DIR = Resolution

MODULE_OBJS = Resolution.o edid.o 915resolution.o

include ../MakeInc.dir