#!/usr/bin/python
# Script to add Wait for Chameleon boot loaders

import sys
import os

vol = str(sys.argv[3])
boot = "/Extra/org.chameleon.Boot.plist"
plist = vol + boot
infile = open(plist, "r")
# check if Wait has been written or not
WaitCheck = False

body = ""

for line in infile:
    # if we finish the tags and haven't written Wait Yet
    if "</dict>" in line and WaitCheck == False:
        line = "        <key>Wait</key>\n"
        line += "        <string>Yes</string>\n"
        line += "</dict>\n"
        WaitCheck = True
        
    body += line
    
infile.close()

outfile = open(plist, "w")
outfile.write(body)
outfile.close()
