#!/bin/bash

set -u

targetVolume="$3"

themeName="@themeName@"
themeDir="@themeDir@"
logName="@LOG_FILENAME@"
logFile="${targetVolume}/$logName"

# Check if target volume exists
if [[ ! -d "$targetVolume" ]]; then
    echo "$targetVolume volume does not exist!" >&2
    exit 1
fi

exec >>"${logFile}" 2>&1

[[ -d "${targetVolume}/Extra/Themes/$themeDir" ]] && echo "Theme $themeName installed"

exit 0
