#!/usr/bin/python
# Script to add UHCIreset for Chameleon boot loaders

import sys
import os

vol = str(sys.argv[3])
boot = "/Extra/org.chameleon.Boot.plist"
plist = vol + boot
infile = open(plist, "r")
# check if UHCIreset has been written or not
UHCIresetCheck = False

body = ""

for line in infile:
    # if we finish the tags and haven't written UHCIreset Yet
    if "</dict>" in line and UHCIresetCheck == False:
        line = "        <key>UHCIreset</key>\n"
        line += "        <string>Yes</string>\n"
        line += "</dict>\n"
        UHCIresetCheck = True
        
    body += line
    
infile.close()

outfile = open(plist, "w")
outfile.write(body)
outfile.close()
