#!/bin/sh
#
# $1: the full path to the installation package; for example:
# /Volumes/Projects/Testing/Simple_Carbon_App.pkg
#
# $2: the full path to the installation destination; for example:
# /Applications
#
# $3: the mountpoint of the destination volume; for example:
# / or /Volumes/External_Drive
# 
# $4: the root directory for the current System folder:
# /

echo "preinstall: Path to installer....... $1"
echo "preinstall: Path to destination..... $2"
echo "preinstall: Path to dest volume..... $3"
echo "preinstall: Root of system folder... $4"

set -x

if [ ! -e "$3" ]
then
    echo "destination volume does not exist!"
    exit 1
fi

# clean up what would otherwise turn into "//" paths
if [ "$3" == "/" ]
then
    dest_vol=""
else
    dest_vol="$3"
fi    

# delete the temporary Chameleon folder

rm -rf "$dest_vol/tmpcham"

echo "Done..."
