#!/usr/bin/python
# Script to add UseAtiROM for Chameleon boot loaders

import sys
import os

vol = str(sys.argv[3])
boot = "/Extra/org.chameleon.Boot.plist"
plist = vol + boot
infile = open(plist, "r")
# check if UseAtiROM has been written or not
UseAtiROMCheck = False

body = ""

for line in infile:
    # if we finish the tags and haven't written UseAtiROM Yet
    if "</dict>" in line and UseAtiROMCheck == False:
        line = "        <key>UseAtiROM</key>\n"
        line += "        <string>Yes</string>\n"
        line += "</dict>\n"
        UseAtiROMCheck = True
        
    body += line
    
infile.close()

outfile = open(plist, "w")
outfile.write(body)
outfile.close()
