#!/usr/bin/python
# Script to add Graphics_Mode for Chameleon boot loaders

import sys
import os
import shutil

vol = str(sys.argv[3])
boot = "/Extra/org.chameleon.Boot.plist"
plist = vol + boot
if not os.path.exists(plist):
    shutil.copy('/Library/Preferences/SystemConfiguration/com.apple.Boot.plist', plist)

infile = open(plist, "r")
# check if Graphics_Mode has been written or not
Graphics_ModeCheck = False

body = ""

for line in infile:
    # if we finish the tags and haven't written Graphics_Mode Yet
    if "</dict>" in line and Graphics_ModeCheck == False:
        line = "        <key>Graphics Mode</key>\n"
        line += "        <string>1280x1024x32</string>\n"
        line += "</dict>\n"
        Graphics_ModeCheck = True
        
    body += line
    
infile.close()

outfile = open(plist, "w")
outfile.write(body)
outfile.close()
